name: calonaplikasi
description: "A new Flutter project."

# Mencegah paket dipublikasikan ke pub.dev secara tidak sengaja.
publish_to: 'none' # Hapus baris ini jika ingin mempublikasikan ke pub.dev

# Versi aplikasi
version: 1.0.0+1

# Environment SDK
environment:
  sdk: ^3.7.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2
  webview_flutter: ^4.0.7
  async: ^2.10.0 # Package async untuk queue logging
  font_awesome_flutter: ^10.0.0 # Untuk ikon Font Awesome
  cupertino_icons: ^1.0.8 # Untuk ikon gaya iOS
  logging: ^1.2.0 # Paket logging untuk debugging dan manajemen log
  intl: ^0.18.1  # Add this line
  youtube_player_flutter: ^9.1.1
  image_picker: ^0.8.7+3 # atau versi stabil lainnya
  lottie: ^2.6.3
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_staggered_animations: ^1.1.0
  flutter_rating_bar: ^4.0.1

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Untuk linter kode Dart yang baik

# Bagian spesifik Flutter
flutter:
  uses-material-design: true # Menggunakan Material Design

  # Menambahkan aset gambar
  assets:
    - assets/images/
    - assets/img/digimize_logo.png
    - assets/img/shopping_bag.png
    - assets/img/palette_brush.png
    - assets/img/community_avatars.png
    - assets/profile/kimjongun.png
    - assets/home/image1.png
    - assets/home/image2.png
    - assets/home/image3.png
    - assets/home/image4.png
    - assets/home/image5.png
    - assets/shop/brosur.png
    - assets/shop/designbook.png
    - assets/shop/designposter.png
    - assets/shop/graphicdesign.png
    - assets/shop/designuiux.png
    - assets/shop/posterdigital.png
    - assets/images/default_profile.png
    

  # Menambahkan font kustom (jika ada)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700